services:
  app:
    image: ghcr.io/excoffierleonard/footage-processor:latest
    restart: unless-stopped
    build:
      context: .
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    environment:
      - YOUTUBE_CREDENTIALS=${YOUTUBE_CREDENTIALS}
    volumes:
      - ./input:/app/input
      - ./output:/app/output
      - ./processed:/app/processed
      - ./failed:/app/failed
